name: Django CI Pipeline

on:
  push:
    branches:
      - main
      - akash
  pull_request:
    branches:
      - main
      - akash

jobs:
  run-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t django-task-manager .

      - name: Run Docker Container
        run: |
          docker run -d --name task_manager_container -p 8000:8000 django-task-manager

      - name: Show Running Containers
        run: |
          docker ps

      - name: Run Tests inside Container
        run: |
          docker exec task_manager_container python manage.py test

      - name: Stop and Remove Container
        run: |
          docker stop task_manager_container
          docker rm task_manager_container
